# Generated by Django 2.2.12 on 2023-07-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='')),
                ('firstname', models.TextField(max_length=60)),
                ('lastname', models.TextField(max_length=60)),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField()),
                ('profession', models.TextField()),
                ('experience', models.IntegerField()),
                ('id_card_number', models.BigIntegerField()),
                ('objective', models.TextField(max_length=300)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Careseeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='')),
                ('firstname', models.TextField(max_length=60)),
                ('lastname', models.TextField(max_length=60)),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('state', models.TextField(max_length=60)),
                ('city', models.TextField(max_length=60)),
                ('address', models.TextField(max_length=80)),
                ('order', models.TextField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
